const actions = Object.freeze({
  ON_FOCUS_DATE_CHANGE: 'ON_FOCUS_DATE_CHANGE',
  ON_FILTERED_CASH_HISTORIES_CHANGE: 'ON_FILTERED_CASH_HISTORIES_CHANGE',
  ON_CASH_HISTORIES_CHANGE: 'ON_CASH_HISTORIES_CHANGE',
  ON_PAYMENTS_CHANGE: 'ON_PAYMENTS_CHANGE',
  ON_CATEGORIES_CHANGE: 'ON_CATEGORIES_CHANGE',
  ON_CASH_HISTORY_CHANGE: 'ON_CASH_HISTORY_CHANGE'
});

export default actions;
